name: 🔬
on:
  push:
    branches:
      - '*'
      - '!test-ci'
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.eslintignore'
      - 'docs/**'
      - 'LICENSE'
jobs:
  test-node-os-coverage:
    name: Node ${{ matrix.node-version }} | ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ '17', '16', '15', '14.15.0' ]
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2

      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Set Local FTP
        if: matrix.os == 'ubuntu-latest'
        run: docker run -d -p 21:21 -e FTP_USER=test -e FTP_PASS=test -e PASV_ADDRESS=127.0.0.1 bogem/ftp

      - name: 📦 Downgrade to minimum required NPM version on minimum required Node.js
        if: matrix.node-version == '14.15.0'
        run: npm i npm@7.0.2 -g

      - name: 📦 Upgrade to latest NPM version on latest Node.js
        if: matrix.node-version == '17'
        run: npm i npm@latest -g

      - name: 📦 Testing Services
        run: npm run test-services

  publish-npmjs:
    name: Publish Package to npmjs
    runs-on: ubuntu-latest
    needs: [ test-node-os-coverage ]
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2

      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'

      - name: 📥 Publishing Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    name: Publish Package to GitHub
    runs-on: ubuntu-latest
    needs: [ test-node-os-coverage, publish-npmjs ]
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2

      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com/wellwelwel'
          scope: '@wellwelwel'

      - name: 📦 Preparing Package
        run: node .github/workflows/publish.js

      - name: 📥 Publishing Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}