name: CI
on: push
jobs:
  test-node-os-coverage:
    name: Node.js
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ '17.x', '16.x', '15.x', '14.15.0' ]
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2
      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 📥 Set Local FTP
        if: matrix.os == 'ubuntu-latest'
        run: docker run -d -p 21:21 -e FTP_USER=test -e FTP_PASS=test -e PASV_ADDRESS=127.0.0.1 bogem/ftp
      - name: 📦 Upgrade to the minimum required NPM version
        if: matrix.node-version == '14.15.0'
        run: npm install -g npm@7.0.2
      - name: 📦 Testing Services
        run: npm run test-services
      - name: ⏪ Checking Previous Step for Linux and macOS
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: (ls "passed" && exit 0) || exit 1
      - name: ⏪ Checking Previous Step for Windows
        if: matrix.os == 'windows-latest'
        run: ls "passed"; if ($?) { exit 0 } else { exit 1 }
  publish-npmjs:
    name: Publish Package to npmjs
    runs-on: ubuntu-latest
    needs: [ test-node-os-coverage ]
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2
      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
      - name: 📥 Publishing Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-github:
    name: Publish Package to GitHub
    runs-on: ubuntu-latest
    needs: [ test-node-os-coverage, publish-npmjs ]
    if: github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2
      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com'
          scope: '@wellwelwel'
      - name: 📦 Preparing Package
        run: node .github/workflows/publish.js
      - name: 📥 Publishing Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}