name: CI
on:
  push:
    branches:
      - main
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - run: npm run test-services
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - run: npm run test-services
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - run: npm run test-services
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com'
          scope: '@wellwelwel'
      - run: node .github/workflows/publish.js
      - run: npm publish || exit 0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}