name: CI
on:
  push:
    branches:
      - main
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ actions/checkout@v2
        uses: actions/checkout@v2
      - name: ⚙️ actions/setup-node@v2
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - name: 📥 Set Local FTP
        run: docker run -d -p 21:21 -p 47400-47470:47400-47470 -v /tmp:/var/ftp:ro -e FTP_USER=test -e FTP_PASS=test123 -e PASV_ADDRESS=127.0.0.1 --name ftp --restart=always bogem/ftp
      - name: 📦 Testing Services with FTP Connection
        run: npm run test-services
      - name: ⏪ Checking Previous Step
        run: (ls "passed" && exit 0) || exit 1
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - name: 📦 Testing Services
        run: npm run test-services
      - name: ⏪ Checking Previous Step
        run: (ls "passed" && exit 0) || exit 1
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - name: 📦 Testing Services
        run: npm run test-services
      - name: ⏪ Checking Previous Step
        run: ls "passed"; if ($?) { exit 0 } else { exit 1 }
  Publish:
    runs-on: ubuntu-latest
    needs: [ Linux, macOS, Windows ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          check-latest: true
          registry-url: 'https://npm.pkg.github.com'
          scope: '@wellwelwel'
      - run: node .github/workflows/publish.js
      - run: npm publish || exit 0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}