name: CI
on: push
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2
      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - name: 📥 Set Local FTP
        run: docker run -d -p 21:21 -e FTP_USER=test -e FTP_PASS=test -e PASV_ADDRESS=127.0.0.1 bogem/ftp
      - run: npm install -g npm@latest
      - name: 📦 Testing Services with FTP Connection
        run: npm run test-services
      - name: ⏪ Checking Previous Step
        run: (ls "passed" && exit 0) || exit 1
  # macOS:
  #   runs-on: macos-latest
  #   steps:
  #     - name: ➕ Actions - Checkout
  #       uses: actions/checkout@v2
  #     - name: ➕ Actions - Setup NodeJS
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.15.0'
  #     - name: 📦 Testing Services
  #       run: npm run test-services
  #     - name: ⏪ Checking Previous Step
  #       run: (ls "passed" && exit 0) || exit 1
  # Windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: ➕ Actions - Checkout
  #       uses: actions/checkout@v2
  #     - name: ➕ Actions - Setup NodeJS
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.15.0'
  #     - name: 📦 Testing Services
  #       run: npm run test-services
  #     - name: ⏪ Checking Previous Step
  #       run: ls "passed"; if ($?) { exit 0 } else { exit 1 }
  Node16:
    runs-on: ubuntu-latest
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v2
      - name: ➕ Actions - Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15.0.0'
          # check-latest: true
      - run: npm -v
      # - name: 📥 Set Local FTP
      #   run: docker run -d -p 21:21 -e FTP_USER=test -e FTP_PASS=test -e PASV_ADDRESS=127.0.0.1 bogem/ftp
      # - name: 📦 Testing Services with FTP Connection
      #   run: npm run test-services
      # - name: ⏪ Checking Previous Step
      #   run: (ls "passed" && exit 0) || exit 1
  # Node17:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ➕ Actions - Checkout
  #       uses: actions/checkout@v2
  #     - name: ➕ Actions - Setup NodeJS
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '17'
  #         check-latest: true
  #     - name: 📥 Set Local FTP
  #       run: docker run -d -p 21:21 -e FTP_USER=test -e FTP_PASS=test -e PASV_ADDRESS=127.0.0.1 bogem/ftp
  #     - name: 📦 Testing Services with FTP Connection
  #       run: npm run test-services
  #     - name: ⏪ Checking Previous Step
  #       run: (ls "passed" && exit 0) || exit 1
  # Publish:
  #   runs-on: ubuntu-latest
  #   needs: [ Linux, macOS, Windows, Node16, Node17 ]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: ➕ Actions - Checkout
  #       uses: actions/checkout@v2
  #     - name: ➕ Actions - Setup NodeJS
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '17'
  #         check-latest: true
  #         registry-url: 'https://npm.pkg.github.com'
  #         scope: '@wellwelwel'
  #     - name: 📦 Preparing Package
  #       run: node .github/workflows/publish.js
  #     - name: 📥 Publishing Package
  #       run: npm publish || exit 0
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}